cache: bundler
language: ruby

services:
  - mysql
  - postgresql

rvm:
  - 2.6.6
  - 2.7.2
  - 3.0.0

before_script:
  - cp test/database.yml.example test/database.yml
  - mysql -e 'create database mass_insert_test;'
  - psql -c 'create database mass_insert_test;' -U postgres

before_install:
  - gem install bundler -v 2.0.2

gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/rails_5.2.gemfile
      rvm: 3.0.0
